apiVersion: v1
kind: Service
metadata:
  name: {{ include "beam.fullname" . }}
  labels:
    {{- include "beam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.publicPort }}
      targetPort: public
      protocol: TCP
      name: public
  selector:
    {{- include "beam.selectorLabels" . | nindent 4 }}
