apiVersion: v1
kind: Service
metadata:
  name: {{ include "denji.fullname" . }}
  labels:
    {{- include "denji.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.privatePort }}
      targetPort: private
      protocol: TCP
      name: private
    - port: {{ .Values.service.publicPort }}
      targetPort: public
      protocol: TCP
      name: public
  selector:
    {{- include "denji.selectorLabels" . | nindent 4 }}