name: beam
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/beam.yml
      - charts/beam/**
jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      project: beam
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the chart version
        id: version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' ./charts/${{ env.project }}/Chart.yaml
      - name: Publish
        run: |
          helm registry login -u ${{ vars.CHARTSHUB_USERNAME }} -p ${{ secrets.CHARTSHUB_TOKEN }} registry-1.docker.io
          helm package charts/${{ env.project }} -d dist
          helm push dist/${{ env.project }}-${{ steps.version.outputs.result }}.tgz oci://registry-1.docker.io/${{ vars.CHARTSHUB_USERNAME }}
