name: main
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/denji.yml
      - charts/denji/**
jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: |
          helm registry login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} registry-1.docker.io
          helm package charts/denji -d dist