name: main
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/denji.yml
      - charts/denji/**
jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: |
          helm registry login -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io/${{ github.repository_owner }}/denji
          helm package charts/denji -d dist
          find ./dist -type f -iname "*.tgz" | xargs -I "{}" helm push "{}" "oci://ghcr.io/${{ github.repository_owner }}/denji:{}"